# Generated by Django 2.2.7 on 2020-02-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('solicitacoes', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de crição', verbose_name='Data e hora de criação')),
                ('comentario', models.CharField(help_text='Texto que ajudará a entender a evolução do serviço/processo', max_length=200, verbose_name='Comentário')),
                ('disponivelCliente', models.BooleanField(default=False, verbose_name='Informação deve ficar disponvível para o cliente?')),
                ('pedido', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido', verbose_name='Pedido relacionado')),
                ('solicitacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Solicitacao', verbose_name='Descreva a solicitação')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status', verbose_name='Status')),
            ],
        ),
    ]
