# Generated by Django 2.2.7 on 2019-12-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('andamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status'),
        ),
    ]
