# Generated by Django 2.2.7 on 2020-01-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('status', '0002_status_empresa'),
        ('andamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status'),
        ),
    ]
