# Generated by Django 2.2.7 on 2020-03-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento',
            name='disponivelCliente',
            field=models.BooleanField(default=False, verbose_name='Marque se deseja enviar esta atualização para o cliente (via App e e-mail)'),
        ),
    ]
