# Generated by Django 2.2.7 on 2020-02-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andamentos', '0001_initial'),
        ('status', '0003_auto_20200218_0911'),
        ('solicitacoes', '0002_auto_20200218_0911'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido', verbose_name='Pedido relacionado'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='solicitacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Solicitacao', verbose_name='Descreva a solicitação'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status', verbose_name='Status'),
        ),
    ]
