# Generated by Django 2.2.7 on 2019-11-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Andamentos',
            new_name='Andamento',
        ),
    ]
