# Generated by Django 2.2.7 on 2020-01-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
        ('andamentos', '0002_auto_20200109_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento',
            name='solicitacao',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Solicitacao'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido'),
        ),
    ]
