# Generated by Django 2.2.7 on 2020-01-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andamentos', '0002_auto_20200122_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='solicitacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Solicitacao'),
        ),
    ]
