# Generated by Django 2.2.7 on 2020-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andamentos', '0002_auto_20200313_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento',
            name='disponivelCliente',
            field=models.BooleanField(default=False, verbose_name='Marque se deseja enviar esta atualização para o cliente via App e e-mail'),
        ),
    ]
