# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andamentos', '0002_auto_20200210_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento',
            name='comentario',
            field=models.CharField(help_text='Texto que ajudará a entender a evolução do serviço/processo', max_length=200, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de crição', verbose_name='Data e hora de criação'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='disponivelCliente',
            field=models.BooleanField(default=False, verbose_name='Informação deve ficar disponvível para o cliente?'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido', verbose_name='Pedido relacionado'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='solicitacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Solicitacao', verbose_name='Descreva a solicitação'),
        ),
        migrations.AlterField(
            model_name='andamento',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status', verbose_name='Status'),
        ),
    ]
