# Generated by Django 3.0.5 on 2020-04-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andamentos', '0003_auto_20200313_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andamento',
            options={'ordering': ['dataHoraCriacao']},
        ),
    ]
