# Generated by Django 3.0.5 on 2020-05-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20200416_1119'),
        ('andamentos', '0004_auto_20200416_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento',
            name='servico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.Servico', verbose_name='Serviço relacionado'),
        ),
    ]
