# Generated by Django 3.0.5 on 2020-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andamentos', '0005_andamento_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento',
            name='comentario',
            field=models.CharField(help_text='Texto que ajudará a entender a evolução do serviço/processo', max_length=500, verbose_name='Comentário'),
        ),
    ]
