# Generated by Django 2.2.7 on 2020-02-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0004_auto_20200204_1124'),
        ('clientes', '0003_auto_20200210_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de crição')),
                ('qtdParcelas', models.IntegerField()),
                ('dataVencimento', models.DateField(help_text='Data de vencimento da primeira parcela')),
                ('valor', models.FloatField(help_text='Insira o valor em R$')),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('servico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='servicos.Servico')),
            ],
        ),
    ]
