# Generated by Django 2.2.7 on 2020-02-28 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dataVencimentoVendedor',
            field=models.DateField(default=django.utils.timezone.now, help_text='As demais contas serão provisionadas mensalmente, respeitando o tempo de duração definido para o vendedor', verbose_name='Data para pagamento da primeira comissão do vendedor'),
            preserve_default=False,
        ),
    ]
