# Generated by Django 2.2.7 on 2020-02-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='qtdParcelas',
            field=models.FloatField(),
        ),
    ]
