# Generated by Django 2.2.7 on 2020-02-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataVencimento',
            field=models.DateField(help_text='As demais cobranças serão provisionadas mensalmente, respeitando a quantidade de cobranças definida', verbose_name='Data de vencimento da primeira cobrança'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='qtdParcelas',
            field=models.IntegerField(verbose_name='Quantidade de cobranças a serem geradas (parcelamento)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status', verbose_name='Status do serviço contratado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(help_text='O valor de cada vencimento (em caso de parcelamento) será calculado pelo sistema', verbose_name='Insira o valor total do serviço contratado'),
        ),
    ]
