# Generated by Django 2.2.7 on 2020-01-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0002_status_empresa'),
        ('servicos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='servico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='servicos.Servico'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status'),
        ),
    ]
