# Generated by Django 2.2.7 on 2019-11-24 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20191124_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='dataHoraPedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Captura automaticamente a data de crição'),
            preserve_default=False,
        ),
    ]
