# Generated by Django 2.2.7 on 2020-02-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
        ('pedidos', '0002_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendedores.Vendedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status'),
        ),
    ]
