# Generated by Django 2.2.7 on 2020-02-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200203_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='qtdParcelas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(help_text='Insira o valor em R$'),
        ),
    ]
