# Generated by Django 2.2.7 on 2020-01-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200120_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
    ]
