# Generated by Django 3.0.5 on 2020-04-15 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20200328_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dataVencimentoContrato',
            field=models.DateField(default=django.utils.timezone.now, help_text='O sistema utilizará o mês a ano indicado para alertá-lo do vencimento', verbose_name='Data de vencimento do contrato'),
            preserve_default=False,
        ),
    ]
