# Generated by Django 2.2.7 on 2019-11-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20191124_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='dataHora',
            new_name='dataHoraCriacao',
        ),
    ]
