# Generated by Django 2.2.7 on 2019-12-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20191204_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='servico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='servicos.Servico'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status'),
        ),
    ]
