# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20200210_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Cliente que contratou'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação', verbose_name='Data e hora de criação'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataVencimento',
            field=models.DateField(verbose_name='Data de vencimento da primeira parcela'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='qtdParcelas',
            field=models.IntegerField(verbose_name='Quantidade de parcelas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='servico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='servicos.Servico', verbose_name='Serviço contratado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='status.Status', verbose_name='Status do serviço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(help_text='O vencimento e valor das parcelas serão calculados pelo sistema', verbose_name='Insira o valor total do serviço contratado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vendedores.Vendedor', verbose_name='Vendedor que realizou a venda'),
        ),
    ]
