# Generated by Django 2.2.7 on 2020-02-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_valorpago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valorPago',
        ),
    ]
