# Generated by Django 3.0.5 on 2020-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
        ('pedidos', '0004_pedido_datavencimentocontrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ManyToManyField(default=None, to='vendedores.Vendedor', verbose_name='Vendedor que realizou a venda (para cálculo de comissão)'),
        ),
    ]
