# Generated by Django 3.0.5 on 2020-04-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200415_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['dataHoraCriacao']},
        ),
    ]
