# Generated by Django 3.0.5 on 2020-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20200416_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valorParcela',
            field=models.FloatField(blank=True, default=0, help_text='Caso preenchido, este campo será utilizado para calcular o valor total do contrato', verbose_name='Valor de cada parcela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(blank=True, help_text='Caso preenchido, este campo será utilizado para calcular o valor de cada parcela do contrato', null=True, verbose_name='Valor total do contrato'),
        ),
    ]
