# Generated by Django 3.0.5 on 2020-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20200417_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='arquivo',
            field=models.FileField(null=True, upload_to='documentos', verbose_name='Anexe o contrato'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataVencimento',
            field=models.DateField(verbose_name='Data de vencimento da primeira cobrança'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataVencimentoContrato',
            field=models.DateField(verbose_name='Data de vencimento do contrato'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataVencimentoVendedor',
            field=models.DateField(verbose_name='Data para pagamento da primeira comissão do vendedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valorParcela',
            field=models.FloatField(blank=True, verbose_name='Valor de cada parcela'),
        ),
    ]
