# Generated by Django 3.0.5 on 2020-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20200417_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos', verbose_name='Anexe o contrato'),
        ),
    ]
