# Generated by Django 3.0.5 on 2020-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_auto_20200522_1042'),
        ('servicos', '0003_auto_20200416_1119'),
        ('pedidos', '0011_auto_20200417_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='servico',
            field=models.ManyToManyField(default=None, related_name='pedidos', to='servicos.Servico', verbose_name='Serviços contratados'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ManyToManyField(default=None, related_name='pedidos', to='vendedores.Vendedor', verbose_name='Vendedor que realizou a venda (para cálculo de comissão)'),
        ),
    ]
