# Generated by Django 3.0.5 on 2020-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_auto_20200715_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='qtdParcelas',
            field=models.IntegerField(default=1, verbose_name='Quantidade de cobranças a serem geradas (parcelamento)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valorParcela',
            field=models.FloatField(default=0, verbose_name='Valor de cada parcela'),
            preserve_default=False,
        ),
    ]
