# Generated by Django 3.0.5 on 2020-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='moeda',
            field=models.CharField(choices=[('R$', 'BRL(R$)'), ('$', 'USA($)'), ('€', 'EURO(€)')], default='R$', max_length=2, verbose_name='Moeda'),
        ),
    ]
