# Generated by Django 3.0.5 on 2020-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_auto_20200718_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(blank=True, help_text='Caso preenchido, este campo será utilizado para calcular o valor de cada parcela do contrato', null=True, verbose_name='Valor Original do contrato'),
        ),
    ]
