# Generated by Django 2.2.7 on 2019-11-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiposServicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoServicos',
            new_name='TiposServicos',
        ),
    ]
