# Generated by Django 2.2.7 on 2019-11-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiposServicos', '0002_auto_20191123_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposServicos',
            new_name='TiposServico',
        ),
    ]
