# Generated by Django 2.2.7 on 2020-02-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação', verbose_name='Data e hora de criação')),
                ('solicitacao', models.CharField(max_length=300, verbose_name='Descreva sua solicitação')),
                ('atendida', models.BooleanField(default=False, verbose_name='Marque esta opção caso sua solicitação tenha sido atendida')),
                ('fechada', models.BooleanField(default=False, verbose_name='Marque esta opção caso a solicitação precise ser fechada, independente de ter sido atendida ou não')),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Cliente que fez a solicitação')),
            ],
        ),
    ]
