# Generated by Django 2.2.7 on 2019-12-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20191123_1429'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente'),
        ),
    ]
