# Generated by Django 2.2.7 on 2019-11-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Quando for Empresa, digitar NomeFantasia', max_length=100)),
                ('nomeContato', models.CharField(help_text='Nome da pessoa que será o contato principal', max_length=100)),
                ('emailContato', models.CharField(help_text='E-mail que será utilizado nas comunicações', max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('endereco', models.CharField(help_text='Endereço contendo Rua e Número', max_length=100)),
                ('complemento', models.CharField(help_text='Exemplo: Sala A, Apartamento 30', max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(help_text='Incluindo traço. Exemplo: 15000-000', max_length=9)),
            ],
        ),
    ]
