# Generated by Django 2.2.7 on 2020-02-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Incluindo traço. Exemplo: 15000-000', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Incluindo traço. Exemplo: 15000-000', max_length=100, null=True),
        ),
    ]
