# Generated by Django 2.2.7 on 2020-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200227_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='appHabilitado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Habilitar cliente a utilizar o App?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='campanha',
            field=models.ManyToManyField(blank=True, null=True, to='campanhas.Campanha', verbose_name='Campanhas que recebeu via sistema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, help_text='Incluindo traço. Exemplo: 15000-000', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Exemplo: Sala A, Apartamento 30', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço contendo Rua e Número', max_length=100, null=True, verbose_name='Rua e número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeContato',
            field=models.CharField(blank=True, help_text='Nome da pessoa que será o contato principal', max_length=100, null=True, verbose_name='Nome da pessoa de contato'),
        ),
    ]
