# Generated by Django 2.2.7 on 2019-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20191123_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Exemplo: Sala A, Apartamento 30', max_length=100),
        ),
    ]
