# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200210_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='campanha',
            field=models.ManyToManyField(blank=True, to='campanhas.Campanha', verbose_name='Campanhas que recebeu via sistema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(help_text='Incluindo traço. Exemplo: 15000-000', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Exemplo: Sala A, Apartamento 30', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Incluindo pontos e traço.', max_length=50, verbose_name='CPF / CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='emailContato',
            field=models.CharField(help_text='E-mail que será utilizado nas comunicações', max_length=100, verbose_name='E-mail da pessoa de contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(help_text='Endereço contendo Rua e Número', max_length=100, verbose_name='Rua e número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Quando for pessoa juridica, digitar o Nome Fantasia', max_length=100, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeContato',
            field=models.CharField(help_text='Nome da pessoa que será o contato principal', max_length=100, verbose_name='Nome da pessoa de contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão social'),
        ),
    ]
