# Generated by Django 2.2.7 on 2020-02-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200227_1448'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('cpf_cnpj', 'empresa'), name='unique_cpf_por_empresa'),
        ),
    ]
