# Generated by Django 2.2.7 on 2019-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
        ('clientes', '0004_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='campanha',
            field=models.ManyToManyField(blank=True, default=None, to='campanhas.Campanha'),
        ),
    ]
