# Generated by Django 2.2.7 on 2020-03-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20200313_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Exemplo: +55(11)99999-9999', max_length=17, null=True),
        ),
    ]
