# Generated by Django 2.2.7 on 2019-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20191218_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='campanha',
            field=models.ManyToManyField(blank=True, to='campanhas.Campanha'),
        ),
    ]
