# Generated by Django 2.2.7 on 2020-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200313_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='campanha',
            field=models.ManyToManyField(blank=True, to='campanhas.Campanha', verbose_name='Campanhas que recebeu via sistema'),
        ),
    ]
