# Generated by Django 3.0.5 on 2020-05-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20200522_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='playerId',
            field=models.CharField(blank=True, help_text='Campo utilizado pelo App, para recebimento de Push notification', max_length=50, null=True),
        ),
    ]
