# Generated by Django 3.0.5 on 2020-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20200526_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='emailContato',
            field=models.EmailField(default='', help_text='E-mail que será utilizado nas comunicações', max_length=254, verbose_name='E-mail da pessoa de contato'),
            preserve_default=False,
        ),
    ]
