# Generated by Django 3.0.5 on 2020-05-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20200526_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='playerId',
            new_name='playerId_onsignal',
        ),
    ]
