# Generated by Django 3.0.5 on 2020-05-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_auto_20200528_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='playerId_onsignal',
            new_name='playerId_onesignal',
        ),
    ]
