# Generated by Django 3.0.5 on 2020-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0009_auto_20200525_1743'),
        ('clientes', '0016_auto_20200529_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='campanha',
            field=models.ManyToManyField(to='campanhas.Campanha', verbose_name='Campanhas que recebeu via sistema'),
        ),
    ]
