# Generated by Django 3.0.5 on 2020-07-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20200609_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Instagram'),
        ),
    ]
