# Generated by Django 2.2.7 on 2020-02-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontas',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Marque esta opção se o Plano de Contas estiver ativo'),
        ),
    ]
