# Generated by Django 2.2.7 on 2020-02-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_contas', '0002_auto_20200219_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontas',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Atenção: 1 único plano de contas se mantém ativo. Se marcou a opção para ativar este plano, o plano que estiver ativo atualmente será inativado.'),
        ),
    ]
