# Generated by Django 2.2.7 on 2020-02-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planos_contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContasGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do grupo/subgrupo')),
                ('natureza', models.CharField(blank=True, choices=[('Contas devedoras', 'Contas devedoras'), ('Contas credoras', 'Contas credoras'), ('Todas', 'Todas')], max_length=50, null=True, verbose_name='Natureza das contas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Grupo ativo?')),
                ('grupoPai', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos_contas_grupos.PlanoContasGrupo', verbose_name='Selecione o grupo ao qual pertence (grupo pai)')),
                ('planoContas', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos_contas.PlanoContas', verbose_name='Selecione o plano de contas ao qual pertence')),
            ],
        ),
    ]
