# Generated by Django 2.2.7 on 2020-02-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos_contas', '0003_auto_20200219_1733'),
        ('planos_contas_grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontasgrupo',
            name='planoContas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos_contas.PlanoContas', verbose_name='Selecione o plano de contas ao qual pertence'),
        ),
        migrations.AlterField(
            model_name='planocontasgrupo',
            name='grupoPai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos_contas_grupos.PlanoContasGrupo', verbose_name='Selecione o grupo ao qual pertence'),
        ),
    ]
