# Generated by Django 2.2.7 on 2020-02-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos_contas_grupos', '0002_auto_20200220_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontasgrupo',
            name='grupoPai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos_contas_grupos.PlanoContasGrupo', verbose_name='Selecione o grupo ao qual pertence (grupo pai)'),
        ),
        migrations.AlterField(
            model_name='planocontasgrupo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do grupo/subgrupo'),
        ),
    ]
