# Generated by Django 2.2.7 on 2020-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_contas_grupos', '0003_auto_20200220_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontasgrupo',
            name='natureza',
            field=models.CharField(choices=[('Contas devedoras', 'Contras devedoras'), ('Contas credoras', 'Contas credoras')], default='', max_length=50, verbose_name='Natureza das contas'),
            preserve_default=False,
        ),
    ]
