# Generated by Django 2.2.7 on 2020-02-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_contas_grupos', '0004_planocontasgrupo_natureza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontasgrupo',
            name='natureza',
            field=models.CharField(blank=True, choices=[('Contas devedoras', 'Contras devedoras'), ('Contas credoras', 'Contas credoras'), ('Todas', 'Todas')], max_length=50, null=True, verbose_name='Natureza das contas'),
        ),
    ]
