# Generated by Django 2.2.7 on 2019-11-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFantasia', models.CharField(help_text='Nome Fantasia da empresas', max_length=100)),
                ('razaoSocial', models.CharField(help_text='Razao Social da empresas', max_length=100)),
                ('cnpj', models.CharField(help_text='CPNJ da empresas, com pontos e traços', max_length=50)),
                ('ruaNum', models.CharField(help_text='Rua e Número do endereço da empresas', max_length=100)),
                ('complemento', models.CharField(help_text='Exemplo: Sala 30 - Bloco A', max_length=50)),
                ('bairro', models.CharField(help_text='Bairro da empresas', max_length=50)),
                ('cep', models.CharField(help_text='CEP da empresas, com traço', max_length=9)),
                ('cidade', models.CharField(help_text='Cidade sede da empresas', max_length=100)),
                ('estado', models.CharField(help_text='UF da empresas', max_length=2)),
            ],
        ),
    ]
