# Generated by Django 2.2.7 on 2020-02-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.CharField(help_text='E-mail de contato da empresa', max_length=100, null=True),
        ),
    ]
