# Generated by Django 2.2.7 on 2020-02-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='inscricaoEstadual',
            field=models.CharField(default='Isenta', help_text='Caso seja isenta, preencha com a palavra ˜Isenta˜', max_length=50, verbose_name='Inscrição estadual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricaoMunicipal',
            field=models.CharField(default='Isenta', help_text='Caso seja isenta, preencha com a palavra ˜Isenta˜', max_length=50, verbose_name='Inscrição municipal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
