# Generated by Django 2.2.7 on 2019-11-24 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Captura automaticamente a data de crição'),
            preserve_default=False,
        ),
    ]
