# Generated by Django 2.2.7 on 2019-11-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_datahora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='dataHora',
        ),
    ]
