# Generated by Django 2.2.7 on 2020-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20200228_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
