# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_logotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(help_text='Bairro da empresas', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(help_text='CEP da empresas, com traço', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(help_text='Cidade sede da empresas', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(help_text='CPNJ da empresas, com pontos e traços', max_length=50, verbose_name='CPF / CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(help_text='Exemplo: Sala 30 - Bloco A', max_length=50, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(help_text='E-mail de contato da empresa', max_length=100, null=True, verbose_name='E-mail de contato'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(help_text='UF da empresas', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=models.FileField(null=True, upload_to='logotipos', verbose_name='Anexe a logotipo para ser exibido no topo da página'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nomeFantasia',
            field=models.CharField(help_text='Nome Fantasia da empresas', max_length=100, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razaoSocial',
            field=models.CharField(help_text='Razao Social da empresas', max_length=100, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruaNum',
            field=models.CharField(help_text='Exemplo: Rua Francisco Chagas, 3434', max_length=100, verbose_name='Rua e Número do endereço da empresa'),
        ),
    ]
