# Generated by Django 2.2.7 on 2020-03-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='token',
        ),
    ]
