# Generated by Django 2.2.7 on 2020-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20200218_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comissao_nome_plano_contas_grupo',
            field=models.CharField(blank='False', max_length=50, verbose_name='Nome do grupo de contas (devedoras), no Plano de Contas, onde as comissões devem ser lançadas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='parcela_nome_plano_contas_grupo',
            field=models.CharField(blank='False', max_length=50, verbose_name='Nome do grupo de contas (credoras), no Plano de Contas, onde as parcelas devem ser lançadas'),
        ),
    ]
