# Generated by Django 3.0.5 on 2020-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_auto_20200416_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(help_text='E-mail de contato da empresa', max_length=254, null=True, verbose_name='E-mail de contato'),
        ),
    ]
