# Generated by Django 3.0.5 on 2020-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_auto_20200522_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_host',
            field=models.CharField(blank='True', help_text='Exemplo: smtp.gmail.com', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_password',
            field=models.CharField(blank='True', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_user',
            field=models.EmailField(blank='True', help_text='Exemplo: atendimento@tabo.com.br', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_port',
            field=models.CharField(blank='True', default=True, help_text='Exemplo: 587', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
