# Generated by Django 3.0.5 on 2020-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_auto_20200526_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email_port',
            field=models.CharField(blank='True', help_text='Exemplo: 587', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_use_tls',
            field=models.BooleanField(blank='True', default=True, null=True),
        ),
    ]
