# Generated by Django 3.0.5 on 2020-05-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_auto_20200526_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email_use_tls',
        ),
    ]
