# Generated by Django 3.0.5 on 2020-05-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_auto_20200526_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='appid_onesignal',
            field=models.CharField(blank=True, help_text='Informação preenchida quando houver App publicado no site Onesignal para a empresa.', max_length=150, null=True),
        ),
    ]
