# Generated by Django 2.2.7 on 2019-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do status que irá ser utilizado para indicar o andamento de um serviço/processo', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
