# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_status_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Status ativo?'),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Dê um nome ao seu status'),
        ),
    ]
