# Generated by Django 3.0.5 on 2020-07-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200416_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='sequencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequência da etapa no fluxo'),
        ),
    ]
