# Generated by Django 3.0.5 on 2020-07-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_status_sequencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['sequencia']},
        ),
    ]
