# Generated by Django 2.2.7 on 2019-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do serviço/processo a ser oferecido', max_length=100)),
                ('descricao', models.CharField(help_text='Descrição ou exemplo do serviço/processo', max_length=100)),
            ],
        ),
    ]
