# Generated by Django 2.2.7 on 2019-11-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiposServicos', '0003_auto_20191123_1412'),
        ('clientes', '0003_auto_20191123_1429'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do serviço/processo a ser oferecido', max_length=100)),
                ('descricao', models.CharField(help_text='Descrição ou exemplo do serviço/processo', max_length=100)),
                ('clientes', models.ManyToManyField(to='clientes.Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiposServicos.TiposServico')),
            ],
        ),
    ]
