# Generated by Django 2.2.7 on 2020-01-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valor',
        ),
    ]
