# Generated by Django 2.2.7 on 2019-12-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
        ),
    ]
