# Generated by Django 2.2.7 on 2020-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Serviço ativo?'),
        ),
    ]
