# Generated by Django 2.2.7 on 2020-01-21 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.IntegerField(default=None, help_text='Insira o valor em R$'),
            preserve_default=False,
        ),
    ]
