# Generated by Django 2.2.7 on 2019-12-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20191204_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='clientes',
        ),
    ]
