# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20200204_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição ou exemplo do serviço a ser oferecido'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa', verbose_name='Empresa que oferece o serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do serviço a ser oferecido'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tiposServicos.TiposServico', verbose_name='Tipo de serviço oferecido'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.FloatField(verbose_name='Valor do serviço a ser oferecido'),
        ),
    ]
