# Generated by Django 2.2.7 on 2019-11-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de crição')),
                ('texto', models.CharField(help_text='Texto a ser enviado', max_length=170)),
                ('tipo', models.CharField(choices=[('sms', 'Freshman'), ('email', 'Sophomore'), ('push', 'Junior'), ('all', 'Senior')], help_text='Tipo de mensagem', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
