# Generated by Django 2.2.7 on 2019-11-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='Templates_mensagem',
        ),
    ]
