# Generated by Django 2.2.7 on 2019-11-27 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mensagens', '0002_auto_20191127_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates_mensagem',
            new_name='Template_mensagem',
        ),
    ]
