# Generated by Django 2.2.7 on 2019-11-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mensagens', '0003_auto_20191127_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_mensagem',
            name='tipo',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('push', 'Push notification'), ('all', 'All')], help_text='Tipo de mensagem', max_length=10),
        ),
    ]
