# Generated by Django 2.2.7 on 2019-12-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('templates_mensagens', '0004_auto_20191127_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_mensagem',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
        ),
    ]
