# Generated by Django 2.2.7 on 2020-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mensagens', '0005_template_mensagem_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_mensagem',
            name='arquivo',
            field=models.FileField(default='', upload_to='msgpadrao'),
            preserve_default=False,
        ),
    ]
