# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mensagens', '0006_template_mensagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_mensagem',
            name='arquivo',
            field=models.FileField(upload_to='msgpadrao', verbose_name='Anexe um arquivo caso deseje enviá-lo junto à mensagem'),
        ),
        migrations.AlterField(
            model_name='template_mensagem',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Mensagem ativa?'),
        ),
        migrations.AlterField(
            model_name='template_mensagem',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação', verbose_name='Data e hora de criação'),
        ),
        migrations.AlterField(
            model_name='template_mensagem',
            name='texto',
            field=models.CharField(max_length=170, verbose_name='Texto da mensagem a ser enviada'),
        ),
        migrations.AlterField(
            model_name='template_mensagem',
            name='tipo',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('push', 'Push notification'), ('all', 'All')], max_length=10, verbose_name='Tipo da mensagem'),
        ),
    ]
