# Generated by Django 2.2.7 on 2020-01-10 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de crição')),
                ('numParcela', models.IntegerField(default=0, help_text='Número da parcela')),
                ('dataVencimento', models.DateField(default=django.utils.timezone.now, help_text='Data de vencimento da parcela')),
                ('valor', models.FloatField(default=0)),
            ],
        ),
    ]
