# Generated by Django 2.2.7 on 2019-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de crição')),
                ('numParcela', models.IntegerField(help_text='Número da parcela')),
                ('dataVencimento', models.DateField(help_text='Data de vencimento da parcela')),
                ('valor', models.FloatField()),
            ],
        ),
    ]
