# Generated by Django 2.2.7 on 2020-02-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0002_parcela_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='pagas',
            field=models.BooleanField(default=False),
        ),
    ]
