# Generated by Django 2.2.7 on 2020-02-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0003_parcela_pagas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcela',
            old_name='pagas',
            new_name='paga',
        ),
    ]
