# Generated by Django 2.2.7 on 2020-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0004_auto_20200204_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='valorPago',
            field=models.FloatField(blank=True, default=0, help_text='Insira o valor em R$'),
            preserve_default=False,
        ),
    ]
