# Generated by Django 2.2.7 on 2020-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0005_parcela_valorpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='valorPago',
            field=models.FloatField(blank=True, help_text='Insira o valor em R$', null=True),
        ),
    ]
