# Generated by Django 2.2.7 on 2019-11-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo da pessoa ou funcionário que terá acesso ao sistema', max_length=100)),
            ],
        ),
    ]
