# Generated by Django 2.2.7 on 2019-12-11 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0002_auto_20191128_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
