# Generated by Django 3.0.5 on 2020-04-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0002_auto_20200414_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empregado',
            options={'ordering': ['nome']},
        ),
    ]
