# Generated by Django 2.2.7 on 2019-12-11 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0003_auto_20191211_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
