# Generated by Django 3.0.5 on 2020-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0004_auto_20200526_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregado',
            name='usuario',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
