# Generated by Django 3.0.5 on 2020-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0005_empregado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empregado',
            name='senha_servidor_email',
            field=models.CharField(default='', help_text='Esta senha será usada para uso de seu e-mail pessoal na comunicação com o cliente. Caso deixe em branco, será utilizado o e-mail padrão da empresa', max_length=25, verbose_name='Senha para autenticação no servidor de e-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empregado',
            name='nome',
            field=models.CharField(help_text='Exemplo: Marcos Oliveira', max_length=100, verbose_name='Nome (forma como a pessoa costuma ser tratada)'),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='senha',
            field=models.CharField(max_length=25, verbose_name='Senha para acesso ao sistema'),
        ),
    ]
