# Generated by Django 3.0.5 on 2020-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0006_auto_20200526_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='senha_servidor_email',
            field=models.CharField(blank=True, help_text='Esta senha será usada para uso de seu e-mail pessoal na comunicação com o cliente. Caso deixe em branco, será utilizado o e-mail padrão da empresa', max_length=25, null=True, verbose_name='Senha para autenticação no servidor de e-mail'),
        ),
    ]
