# Generated by Django 2.2.7 on 2020-02-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos_contas_grupos', '0006_auto_20200221_1217'),
        ('contasPagar', '0002_contapagar_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='grupoConta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='planos_contas_grupos.PlanoContasGrupo', verbose_name='Lançar conta em qual grupo do Plano de Contas'),
            preserve_default=False,
        ),
    ]
