# Generated by Django 2.2.7 on 2020-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasPagar', '0003_contapagar_grupoconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='dataPagamento',
            field=models.DateField(default=None, null=True, verbose_name='Data de efetivação do pagamento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='descricaoConta',
            field=models.CharField(default='', max_length=100, verbose_name='Descrição da conta a pagar'),
            preserve_default=False,
        ),
    ]
