# Generated by Django 2.2.7 on 2020-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasPagar', '0004_auto_20200223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='dataPagamento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de efetivação do pagamento'),
        ),
    ]
