# Generated by Django 3.0.5 on 2020-04-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contaspagar', '0006_contapagar_vendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['dataVencimento']},
        ),
    ]
