# Generated by Django 3.0.5 on 2020-04-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contaspagar', '0009_auto_20200417_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['vendedor__nome', 'pedido__cliente__nome', 'dataVencimento', 'dataHoraCriacao']},
        ),
    ]
