# Generated by Django 2.2.7 on 2020-02-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_empresa_logotipo'),
        ('clientes', '0003_auto_20200210_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Quando for Empresa, digitar NomeFantasia', max_length=100)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Incluindo pontos e traço.', max_length=50)),
                ('nomeContato', models.CharField(help_text='Nome da pessoa que será o contato principal', max_length=100)),
                ('emailContato', models.CharField(help_text='E-mail que será utilizado nas comunicações', max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('endereco', models.CharField(help_text='Endereço contendo Rua e Número', max_length=100)),
                ('complemento', models.CharField(blank=True, help_text='Exemplo: Sala A, Apartamento 30', max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(help_text='Incluindo traço. Exemplo: 15000-000', max_length=9)),
                ('percentual_bonificacao', models.FloatField(help_text='Percentual que o vendedor tem direito sobre o valor das parcelas pagas', null=True)),
                ('duracao_em_meses', models.IntegerField(help_text='Quantidade de meses que o vendedor deve ser bonificado.', null=True)),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
            ],
        ),
    ]
