# Generated by Django 2.2.7 on 2020-02-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Quando for Empresa, digitar NomeFantasia', max_length=100, verbose_name='Nome completo')),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão social')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Incluindo pontos e traço.', max_length=50, verbose_name='CPF / CNPJ')),
                ('nomeContato', models.CharField(help_text='Nome da pessoa que será o contato principal', max_length=100, verbose_name='Nome da pessoa de contato')),
                ('emailContato', models.CharField(help_text='E-mail que será utilizado nas comunicações', max_length=100, verbose_name='E-mail da pessoa de contato')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('endereco', models.CharField(help_text='Endereço contendo Rua e Número', max_length=100, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, help_text='Exemplo: Sala A, Apartamento 30', max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(help_text='Incluindo traço. Exemplo: 15000-000', max_length=9, verbose_name='CEP')),
                ('percentual_bonificacao', models.FloatField(help_text='Percentual que o vendedor tem direito sobre o valor das parcelas pagas', null=True, verbose_name='Percentual de bonificação')),
                ('duracao_em_meses', models.IntegerField(help_text='Quantidade de meses que o vendedor deve ser bonificado.', null=True, verbose_name='Duração da bonificação (em meses)')),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Vendedor é um cliente? Selecione o cliente, para que a comissão seja abatida dos próximos pagamentos')),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa', verbose_name='Empresa a qual pertence')),
            ],
        ),
    ]
