# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cep',
            field=models.CharField(help_text='Incluindo traço. Exemplo: 15000-000', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Vendedor é um cliente? Selecione o cliente, para que a comissão seja abatida dos próximos pagamentos'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='complemento',
            field=models.CharField(blank=True, help_text='Exemplo: Sala A, Apartamento 30', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Incluindo pontos e traço.', max_length=50, verbose_name='CPF / CNPJ'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='duracao_em_meses',
            field=models.IntegerField(help_text='Quantidade de meses que o vendedor deve ser bonificado.', null=True, verbose_name='Duração da bonificação (em meses)'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='emailContato',
            field=models.CharField(help_text='E-mail que será utilizado nas comunicações', max_length=100, verbose_name='E-mail da pessoa de contato'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa', verbose_name='Empresa a qual pertence'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco',
            field=models.CharField(help_text='Endereço contendo Rua e Número', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome',
            field=models.CharField(help_text='Quando for Empresa, digitar NomeFantasia', max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nomeContato',
            field=models.CharField(help_text='Nome da pessoa que será o contato principal', max_length=100, verbose_name='Nome da pessoa de contato'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='percentual_bonificacao',
            field=models.FloatField(help_text='Percentual que o vendedor tem direito sobre o valor das parcelas pagas', null=True, verbose_name='Percentual de bonificação'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão social'),
        ),
    ]
