# Generated by Django 2.2.7 on 2020-01-22 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquivos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente'),
        ),
    ]
