# Generated by Django 2.2.7 on 2020-01-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0002_arquivo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente'),
        ),
    ]
