# Generated by Django 2.2.7 on 2020-01-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0003_auto_20200122_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='media'),
        ),
    ]
