# Generated by Django 2.2.7 on 2020-01-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0004_auto_20200122_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='documentos'),
        ),
    ]
