# Generated by Django 2.2.7 on 2020-01-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0007_auto_20200123_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='media'),
        ),
    ]
