# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0009_auto_20200123_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='documentos', verbose_name='Anexe o documento'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do documento'),
        ),
    ]
