# Generated by Django 2.2.7 on 2020-02-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação.', verbose_name='Data e hora de criação')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da campanha')),
                ('dataHoraAtivacao', models.DateTimeField(help_text='Quando as mensagens de alerta da campanha devem ser disparadas. Ex: 12/12/2020 10:00:00', verbose_name='Quando a campanha deve ser exibida?')),
                ('dataHoraInativacao', models.DateTimeField(help_text='Quando a campanha deve tornar-se inativa. Ex: 12/12/2020 10:00:00', verbose_name='Quando a campanha deve parar de ser exibida?')),
                ('arquivo', models.FileField(upload_to='campanhas', verbose_name='Anexe uma imagem caso deseje')),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa', verbose_name='Empresa')),
            ],
        ),
    ]
