# Generated by Django 2.2.7 on 2020-01-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_campanha_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='dataHoraAtivacao',
            field=models.DateTimeField(help_text='Quando as mensagens de alerta da campanha devem ser disparadas. Ex: 12/12/2020 10:00:00'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação.'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='dataHoraInativacao',
            field=models.DateTimeField(help_text='Quando a campanha deve tornar-se inativa. Ex: 12/12/2020 10:00:00'),
        ),
    ]
