# Generated by Django 2.2.7 on 2020-04-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_campanha_texto_campanha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='texto_campanha',
            field=models.CharField(max_length=140, verbose_name='Texto da campanha (em 140 caracteres)'),
        ),
    ]
