# Generated by Django 2.2.7 on 2020-01-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_auto_20200120_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='arquivo',
            field=models.FileField(default='', upload_to='campanhas'),
            preserve_default=False,
        ),
    ]
