# Generated by Django 3.0.5 on 2020-04-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_auto_20200408_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='texto_campanha',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Texto da campanha (em até 140 caracteres)'),
        ),
    ]
