# Generated by Django 2.2.7 on 2020-02-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_campanha_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='arquivo',
            field=models.FileField(upload_to='campanhas', verbose_name='Anexe uma imagem caso deseje'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='dataHoraAtivacao',
            field=models.DateTimeField(help_text='Quando as mensagens de alerta da campanha devem ser disparadas. Ex: 12/12/2020 10:00:00', verbose_name='Quando a campanha deve ser exibida?'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='dataHoraCriacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação.', verbose_name='Data e hora de criação'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='dataHoraInativacao',
            field=models.DateTimeField(help_text='Quando a campanha deve tornar-se inativa. Ex: 12/12/2020 10:00:00', verbose_name='Quando a campanha deve parar de ser exibida?'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da campanha'),
        ),
    ]
