# Generated by Django 3.0.5 on 2020-04-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0005_auto_20200414_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanha',
            options={'ordering': ['dataHoraAtivacao']},
        ),
    ]
