# Generated by Django 2.2.7 on 2019-11-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(help_text='Exemplo: Sala 30 - Bloco A', max_length=50),
        ),
    ]
