# Generated by Django 2.2.7 on 2020-02-20 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraCriacao', models.DateTimeField(auto_now_add=True, help_text='Captura automaticamente a data de criação', verbose_name='Data e hora de criação')),
                ('numParcela', models.IntegerField(default=0, verbose_name='Número da parcela')),
                ('dataVencimento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de vencimento da parcela')),
                ('valor', models.FloatField(default=0, verbose_name='Valor a ser pago')),
                ('paga', models.BooleanField(default=False, verbose_name='Parcela está paga?')),
                ('valorPago', models.FloatField(blank=True, null=True, verbose_name='Valor pago em R$')),
                ('dataPagamento', models.DateField(default=None, null=True, verbose_name='Data de efetivação do recebimento')),
                ('descricaoConta', models.CharField(max_length=100, verbose_name='Descrição da conta a receber')),
            ],
        ),
    ]
