# Generated by Django 2.2.7 on 2020-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasReceber', '0003_contareceber_grupoconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='dataPagamento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de efetivação do recebimento'),
        ),
    ]
