# Generated by Django 3.0.5 on 2020-04-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasreceber', '0003_auto_20200311_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contareceber',
            options={'ordering': ['dataVencimento']},
        ),
    ]
