# Generated by Django 3.0.5 on 2020-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasreceber', '0005_contareceber_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos', verbose_name='Anexe o documento da conta'),
        ),
    ]
